// react/client/src/App.js
import React, { useCallback } from "react"
import { useDispatch, useSelector } from "react-redux"
import {
	Route,
	Link,
	Routes,
	BrowserRouter,
} from "react-router-dom"

import "bootstrap/dist/css/bootstrap.min.css"
import "./App.css"

import Login from "./components/auth/Login"
import Register from "./components/auth/Register"
import Home from "./components/Home"

import { logout } from "./components/slice/authSlice"

const App = () => {
	const { user: currentUser } = useSelector((state) => state.auth)
	const dispatch = useDispatch()

	const logOut = useCallback(() => {
		dispatch(logout())
	}, [dispatch])

	return (
		<BrowserRouter>
			<div>
				<nav className="navbar navbar-expand navbar-dark bg-dark">
					<Link to={"/"} className="navbar-brand">
						Ticket APP
					</Link>
					<div className="navbar-nav mr-auto">
						<li className="nav-item">
							<Link to={"/"} className="nav-link">
								Tickets
							</Link>
						</li>
					</div>

					{currentUser ? (
						<div className="navbar-nav ml-auto">
							<li className="nav-item">
								<a
									href="/login"
									className="nav-link"
									onClick={logOut}
								>
									LogOut
								</a>
							</li>
						</div>
					) : (
						<div className="navbar-nav ml-auto">
							<li className="nav-item">
								<Link to={"/login"} className="nav-link">
									Login
								</Link>
							</li>

							<li className="nav-item">
								<Link to={"/register"} className="nav-link">
									Sign Up
								</Link>
							</li>
						</div>
					)}
				</nav>

				<div>
					<Routes>
						<Route exact path="/" element={<Home/>} />
						<Route exact path="/ticket" element={<Home/>} />
						<Route exact path="/login" element={<Login/>} />
						<Route exact path="/register" element={<Register/>} />
					</Routes>
				</div>
			</div>
		</BrowserRouter>
	)
}

export default App

// angular/client/src/app/app.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from './_services/auth.service';
import { TokenStorageService } from './_services/token-storage.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  showAdminBoard = false;
  showModeratorBoard = false;
  username?: string;

  constructor(
    readonly authService:AuthService,
    private tokenStorageService: TokenStorageService,
    private router: Router,
  ) {}

  ngOnInit(): void {
    this.authService.isLoggedIn = !!this.tokenStorageService.getToken();
    

    if (this.authService.isLoggedIn) {
      const user = this.tokenStorageService.getUser();
      this.username = user.username;
    }
  }

  logout(): void {
    this.tokenStorageService.signOut();
    this.router.navigate(['/login']);
  }
}

<div id="app">
  <nav class="navbar navbar-expand navbar-dark bg-dark">
    <a href="#" class="navbar-brand">Token web app</a>
    <a href="/ticket" class="navbar-brand">Tickets</a>
    <ul class="navbar-nav ml-auto" *ngIf="!this.authService.isLoggedIn">
      <li class="nav-item">
        <a href="/register" class="nav-link" routerLink="register">Sign Up</a>
      </li>
      <li class="nav-item">
        <a href="/login" class="nav-link" routerLink="login">Login</a>
      </li>
    </ul>

    <ul class="navbar-nav ml-auto" *ngIf="this.authService.isLoggedIn">
      <li class="nav-item">
        <a href="/profile" class="nav-link" routerLink="profile">{{username}}</a>
      </li>
      <li class="nav-item">
        <a href class="nav-link" (click)="logout()">LogOut</a>
      </li>
    </ul>
  </nav>

  <div class="container">
    <!-- <app-login [isLoggedIn]="isLoggedIn"></app-login> -->
    <router-outlet></router-outlet>
  </div>
</div>
